server:
  port: 8082
  # servlet:
  #   context-path: /
  #   encoding:
  #     charset: utf-8
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false # Print additional trace information
        web-allow-others: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234 

logging:
  level:
    '[site.metacoding.miniproject2]': DEBUG